CREATE TABLE [dbo].[OWNER](
	[Owner_ID] [int] NOT NULL,
	[Name][nvarchar](30) NOT NULL,
	[Surname][nvarchar](30) NOT NULL,
	[Bdate][date] NOT NULL,
	[Gender][nvarchar](10) NOT NULL,
	CONSTRAINT [PK_OWNERID] PRIMARY KEY CLUSTERED 
(
	[Owner_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[COACH](
	[Coach_ID] [int] NOT NULL,
	[Name][nvarchar](30) NOT NULL,
	[Surname][nvarchar](30) NOT NULL,
	[Bdate][date] NOT NULL,
	[Gender][bit] NOT NULL,
	[Email][nvarchar](50) NOT NULL,
	CONSTRAINT [PK_COACHID] PRIMARY KEY CLUSTERED 
(
	[Coach_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 

CREATE TABLE [dbo].[USER](
	[User_ID] [int] NOT NULL,
	[Name][nvarchar](30) NOT NULL,
	[Surname][nvarchar](30) NOT NULL,
	[Bdate][date] NOT NULL,
	[Gender][bit] NOT NULL,
	[Email][nvarchar](50) NOT NULL,
	[Medical_History][nvarchar](100) NOT NULL,
	[Age][int] NOT NULL,
	Membership_ID[int] NOT NULL,

	CONSTRAINT [PK_USERID] PRIMARY KEY CLUSTERED 
(
	[User_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

CREATE TABLE [dbo].[PERSONAL_TRAINING](
	[PT_ID][int] NOT NULL,
	[Day][date] NOT NULL,
	[Time][time] NOT NULL,
	[Coach_ID][int] NOT NULL,
	[User_ID][int] NOT NULL,
CONSTRAINT [PK_PERSONAL_TRAINING] PRIMARY KEY CLUSTERED 
(
	[PT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE [dbo].[CLASS](
	[ClassID][int] NOT NULL,
	[Name][nvarchar](30) NOT NULL,
	[Day][date] NOT NULL,
	[Time][time] NOT NULL,
	[Num_of_Prticipant][int] NOT NULL,
	[Coach_ID][int] NOT NULL,
	[User_ID][int] NOT NULL,
CONSTRAINT [PK_CLASSID] PRIMARY KEY CLUSTERED 
(
	[ClassID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 

CREATE TABLE [dbo].[ACCOUNT](
	[AccountID][int] NOT NULL,
	[username][nvarchar](30) NOT NULL,
	[password][nvarchar](30) NOT NULL,
	[Owner_ID][int] NULL,
	[Coach_ID][int] NULL,
	[User_ID][int] NULL,
CONSTRAINT [PK_ACOUNTID] PRIMARY KEY CLUSTERED 
(
	[AccountID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 

CREATE TABLE [dbo].[Membership](
	[M_ID][int] NOT NULL,
	[EndDay][date] NOT NULL,
	[StartDay][date] NOT NULL,
	[7DaysLeft][date] NOT NULL,

CONSTRAINT [PK_M_ID] PRIMARY KEY CLUSTERED 
(
	[M_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 

CREATE TABLE [dbo].[INVOICE](
	[I_ID][int] NOT NULL,
	[DateOfInvoice][date] NOT NULL,
	[M_ID][int] NOT NULL,
	[P_ID][int] NOT NULL,

CONSTRAINT [PK_I_ID] PRIMARY KEY CLUSTERED 
(
	[I_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 


CREATE TABLE [dbo].[PACKAGES](
	[P_ID][int] NOT NULL,
	[Price][int] NOT NULL,
	[Description][nvarchar](100) NOT NULL,

CONSTRAINT [PK_P_ID] PRIMARY KEY CLUSTERED 
(
	[P_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] 

ALTER TABLE [PERSONAL_TRAINING] WITH CHECK ADD CONSTRAINT [COACHIDFK]
	FOREIGN KEY(Coach_ID) REFERENCES COACH(Coach_ID);
	
ALTER TABLE [PERSONAL_TRAINING] WITH CHECK ADD CONSTRAINT [USERIDFK]
	FOREIGN KEY([User_ID]) REFERENCES [USER]([User_ID]);

ALTER TABLE [CLASS] WITH CHECK ADD CONSTRAINT [CLASS_COACHIDFK]
	FOREIGN KEY(Coach_ID) REFERENCES COACH(Coach_ID);
	
ALTER TABLE [CLASS] WITH CHECK ADD CONSTRAINT [CLASS_USERIDFK]
	FOREIGN KEY([User_ID]) REFERENCES [USER]([User_ID]);

ALTER TABLE [ACCOUNT] WITH CHECK ADD CONSTRAINT [ACCOUTN_COACHIDFK]
	FOREIGN KEY(Coach_ID) REFERENCES COACH(Coach_ID);
	
ALTER TABLE [ACCOUNT] WITH CHECK ADD CONSTRAINT [ACCOUTN_USERIDFK]
	FOREIGN KEY([User_ID]) REFERENCES [USER]([User_ID]);

ALTER TABLE [ACCOUNT] WITH CHECK ADD CONSTRAINT [ACCOUTN_OWNERIDFK]
	FOREIGN KEY([Owner_ID]) REFERENCES [OWNER]([Owner_ID]);

ALTER TABLE [USER] WITH CHECK ADD CONSTRAINT [User_M_IDFK]
	FOREIGN KEY(Membership_ID) REFERENCES MEMBERSHIP(M_ID);

ALTER TABLE INVOICE WITH CHECK ADD CONSTRAINT [INVOICE_M_IDFK]
	FOREIGN KEY(M_ID) REFERENCES MEMBERSHIP(M_ID);

ALTER TABLE INVOICE WITH CHECK ADD CONSTRAINT [P_IDFK]
	FOREIGN KEY(P_ID) REFERENCES PACKAGES(P_ID);